name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_action_in_vm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run action
        uses: ./

      - name: Test usage
        run: |
          sudo apt-get install -y strace
          sudo strace -ff -oapt-eatmydata.trace apt-get install -y hello
          ! grep '^fsync' apt-eatmydata.trace*

      - name: Test package installation without apt set up with eatmydata
        run: |
          sudo rm /etc/apt/apt.conf.d/25-eatmydata-action
          sudo strace -ff -oapt-eatmydata.trace apt-get reinstall -y hello
          grep -m 3 '^fsync' apt-eatmydata.trace*

  test_action_in_container:
    strategy:
      matrix:
        container: ["ubuntu:rolling", "debian:stable"]
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v4
      - name: Run action
        uses: ./

      - name: Test usage
        run: |
          apt-get install -y strace
          strace -ff -oapt-eatmydata.trace apt-get install -y hello
          ! grep '^fsync' apt-eatmydata.trace*

      - name: Test package installation without apt set up with eatmydata
        run: |
          rm /etc/apt/apt.conf.d/25-eatmydata-action
          strace -ff -oapt-eatmydata.trace apt-get reinstall -y hello
          grep -m 3 '^fsync' apt-eatmydata.trace*
